feature:
  - feature/**
  - "**/feature/**"

fix:
  - fix/**
  - "**/fix/**"

docs:
  - docs/**
  - "**/docs/**"
  - "**/*.md"

chore:
  - chore/**
  - "**/chore/**"
  - .github/**

release:
  - release/**
  - "**/release/**"
